# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Pull Request

on: pull_request

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  checks:
    name: Build & Unit Test
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install --immutable --immutable-cache

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build
        env:
          NODE_ENV: production

      - name: Run Tests
        run: yarn test
